name: Code Quality Checks

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint --if-present || npx eslint src/ tests/ --ext .js,.jsx,.ts,.tsx
    
    - name: Run Prettier check
      run: npm run format:check --if-present || npx prettier --check src/ tests/

  test-run:
    name: Test Runner
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test --if-present || npx jest
    
    - name: Run test coverage
      run: npm run test:coverage --if-present || npx jest --coverage

  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build --if-present
    
    - name: Check build artifacts
      run: |
        if [ -d "dist" ]; then
          echo "Build artifacts found in dist/ directory"
          ls -la dist/
        elif [ -d "build" ]; then
          echo "Build artifacts found in build/ directory"
          ls -la build/
        else
          echo "No build artifacts directory found, checking for other outputs"
          ls -la
        fi